# Generated by Django 3.2.4 on 2021-06-25 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('channel_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('uploads_id', models.CharField(max_length=64, unique=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('thumbnail', models.URLField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hol.youtubechannel')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hol.youtubechannel')),
            ],
        ),
    ]
