# Generated by Django 3.2.4 on 2021-07-01 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
